#index:
#    path: /
#    controller: App\Controller\DefaultController::index
authentication_token:
    path:       /authentication_token
    methods: ['POST']
gesdinet_jwt_refresh_token:
    path:       /authentication_token/refresh
    methods: ['POST']
    controller: gesdinet.jwtrefreshtoken::refresh
payment_intent:
    path:       /create-payment-intent
    methods: ['POST']
    controller: App\Controller\PaymentIntentController
